string type_name
string type_version_hash
---
# True if the type description information is available and populated in the response
bool successful
# Empty if 'successful' was true, otherwise contains details on why it failed
string failure_reason

# The idl or msg file name
string type_description_raw_file_name
# The idl or msg file, with comments and whitespace
# The file extension and/or the contents can be used to determine the format
string type_description_raw
# The parsed type description which can be used programmatically
TypeDescription type_description

# Key-value pairs of extra information.
string[] extra_information_keys
string[] extra_information_values
