# Parameter to test if it exists.
rcl_interfaces/ParameterDescription[] parameter_descriptions

---

# Whether each requested parameter exists or not.
# Each element corresponds to the list in the request.
bool[] result
