# The list of parameter groups to query.
string[] parameter_group
bool recurse

---

# All parameters under the parameter_group defined. Recursive if recurse is set.
rcl_interfaces/ParameterDescription[] parameter_descriptions

# The set of subgroups within the queried groups (full path)
string[] sub_groups
