
string[] parameter_group
bool recurse

---

# All parameters under the prefixes defined. Recursive if recurse is set.
rcl_interfaces/ParamDescription[] param_descriptions

# The set of subgroups within the queried groups (full path)
string[] sub_groups
