# Fields always added to goal requests
uint8[16] uuid
# Fields added by user code
#goal definition
int32 order
---
# service response fields are the same for all actions
bool accepted
action_msgs/GoalInfo goal
