# Cancel one or more goals with the following policy:
#
# - If the goal ID is zero and timestamp is zero, cancel all goals.
# - If the goal ID is zero and timestamp is not zero, cancel all goals accepted
#   at or before the timestamp.
# - If the goal ID is not zero and timestamp is zero, cancel the goal with the
#   given ID regardless of the time it was accepted.
# - If the goal ID is not zero and timestamp is not zero, cancel the goal with
#   the given ID and all goals accepted at or before the timestamp.

# Goal info containing an ID and timestamp
GoalInfo goal_info
---
# Response codes
# Indicates the request was accepted.
# One or more goals have transitioned to the CANCELING state.
# The goals_canceling list is empty.
int8 RESPONSE_OK=0
# Indicates the request was rejected.
# No goals have transitioned to the CANCELING state.
# The goals_canceling list is empty.
int8 RESPONSE_REJECTED=1
# Indicates the requested goal ID does not exist.
# No goals have transitioned to the CANCELING state.
# The goals_canceling list is empty.
int8 RESPONSE_UNKNOWN_GOAL_ID=2
# Indicates the goal is not cancelable because it is already in a terminal state.
# No goals have transitioned to the CANCELING state.
# The goals_canceling list is empty.
int8 RESPONSE_GOAL_TERMINATED=3

# Reponse code
int8 response
# Goals that accepted the cancel request
GoalInfo[] goals_canceling
